### ISSUE TITLE
GPS doesn't work

### ISSUE THREAD

**Issue by zhaofengli** [blumonks/android_device_blu_p6601#5]
We can probably borrow something [here](https://github.com/danielhk/android_hardware_lenovo_aio_otfp/tree/cm-14.1/gps).

Reference: https://forum.xda-developers.com/k3-note/orig-development/rom-custom-nougat-roms-k-3-note-t3513466

**Comment by zhaofengli** [comment]
... and it now works flawlessly. Pushing the required changes now.

**Comment by zhaofengli** [comment]
@jianC Could you try making a full build with the manifest? Could use more tests before closing this one.

**Comment by natekc** [comment]
Sure, I'll start a clean build right now.

**Comment by natekc** [comment]
Verified working with GPS Test :) Closing for now.
